language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dockerluis/dockerproject -f Dockerfile.dev .

script:
  - docker run -e CI=true dockerluis/dockerproject npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-project"
  env: "Dockerproject-env"
  bucket_name: "elasticbeanstalk-us-east-2-003177429608"
  bucket_path: "docker-project"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
